### ISSUE TITLE
 How is zsh and oh-my-zsh installed on Windows?

### ISSUE THREAD

**Issue by ThSGM** [2KAbhishek/Winfiles#4]
### Description of the bug

I've been reading the config/.zshrc file and also the installation components suggested in setup.ps1. 

Given what the procedure is, it looks like we need both zsh and oh-my-zsh installed. My understanding is that oh-my-zsh might be trivially installed, but I could not find any indication that it had. Nor could I find the status of zsh. 

### Steps To Reproduce

Described above.

**Comment by 2KAbhishek** [comment]
Hey, thanks for opening up the issue, but zsh and is in fact not installed on windows due to compatibility issues, this config uses powershell as the shell (although I would prefer zsh!)

I have added the symlink for zsh so that if there's any configs I quickly want to check and modify, I can do that
